-- Crea la tabla audit_logs si no existe
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  fecha_creacion timestamp with time zone default now() not null,
  usuario text not null,
  accion text not null,
  modulo text not null,
  detalles text not null,
  ip text
);

-- Habilitar RLS
alter table public.audit_logs enable row level security;

-- Políticas (compatibles con Postgres 15: sin IF NOT EXISTS)
-- Primero eliminamos si ya existen para que sea idempotente
drop policy if exists "allow insert audit logs" on public.audit_logs;
create policy "allow insert audit logs" on public.audit_logs
  for insert
  to anon, authenticated
  with check (true);

drop policy if exists "allow read audit logs" on public.audit_logs;
create policy "allow read audit logs" on public.audit_logs
  for select
  to anon, authenticated
  using (true);

-- Índices útiles
create index if not exists audit_logs_fecha_creacion_idx on public.audit_logs (fecha_creacion desc);
create index if not exists audit_logs_accion_idx on public.audit_logs (accion);
create index if not exists audit_logs_modulo_idx on public.audit_logs (modulo);
